server:
  port: 9201
service-url:
  user-service: http://localhost:8201
spring:
  cloud:
    gateway:
      routes:
        - id: time_route # 路由的ID
          uri: ${service-url.user-service}  # 匹配后路由地址
          predicates:  # 断言,路径相匹配的进行路由
            - After=2020-04-34T16:30:00+08:00[Asia/Shanghai] # 在指定时间之后的请求会匹配该路由
            - Before=2020-04-34T16:30:00+08:00[Asia/Shanghai] # 在指定时间之前的请求会匹配该路由
            - Between=2020-04-34T16:30:00+08:00[Asia/Shanghai] # 在指定时间区间内的请求会匹配该路由
            - Cookie=username,admin # 带有指定Cookie的请求会匹配该路由 username=admin
            - Header=X-Request-Id, \d+  # 带有指定请求头的请求会匹配该路由X-Request-Id:123
            - Host=**.ktz.com # 带有指定host的请求会匹配该路由 Host:www.ktz.com
            - Method=GET # 发送指定方法的请求会匹配该路由
            - Path=/user/{id} # 发送指定路径的请求会匹配该路由/user/1
            - Query=username # 带有指定查询参数的请求会匹配该路由
            - RemoteAddr=192.168.1.1/24 # 从指定远程地址发起的请求可以匹配该路由
            - Weight=group1,8 # 使用权重来路由响应请求