server:
  port: 9201
service-url:
  user-service: http://localhost:8201
spring:
  cloud:
    gateway:
      routes:
        - id: hystrix_route # 路由的ID
          uri: http://localhost:8201
          predicates:  # 断言,路径相匹配的进行路由
            - Method=GET
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback