server:
  port: 8905
spring:
  application:
    name: config-security-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kaituozhesh/springcloud-config.git
          username: asd
          password: asd
          clone-on-start: true
  security:
    user:
      name: admin
      password: 123456