server:
  port: 8003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: rep2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://rep1:8002/eureka/