server:
  port: 8002
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: rep1 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://rep2:8003/eureka/